# .github/workflows/main_tooljet-portal.yml
name: Build and deploy Node.js app to Azure Web App - tooljet-portal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build

      # Stage EVERYTHING the app needs to run:
      # - .next/standalone (contains server.js and bundled server code)
      # - .next/static (client assets)
      # - public/ (if present)
      - name: Prepare runtime bundle
        run: |
          set -e
          rm -rf out
          mkdir -p out/.next
          # standalone server bundle
          cp -r .next/standalone out/.next/standalone
          # static assets expected at .next/static
          cp -r .next/static out/.next/static
          # public assets if any
          if [ -d public ]; then cp -r public out/public; fi
          # (Optional) include minimal metadata
          cp package.json out/package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: out
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98020FFF38984CA18D547CF7BE89EDF7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_641A0B9E757B4858ACEFB8DC16192511 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51F55399101542B98B1D77B4A8CBD801 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tooljet-portal'
          slot-name: 'Production'
          package: .
